name: Generate Documentation

on: [ workflow_dispatch, repository_dispatch ]

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm i
      - name: Generate Documentation
        run: npm run generate:doc

      - name: Generate History
        run: npm run generate:changelog

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add docs -f
          git commit -m "docs: Generate documentation."
          git push origin master